import * as THREE from 'three';
import { stubBrowserGlobals, collectTriangles, groundTriangles, rasterise, writePng } from '../scripts/lib/softRaster.mjs';
stubBrowserGlobals();
const { buildProp } = await import('../src/generators/props.js');
const g = buildProp('tower-great', 1); g.updateMatrixWorld(true);
const tris = collectTriangles(g);
groundTriangles(60, tris);
const cam = new THREE.PerspectiveCamera(40, 1, 0.5, 800);
cam.position.set(6, 12, 62); cam.lookAt(0, 10, 20);
const { px } = rasterise({ tris, camera: cam, w: 700, h: 700 });
writePng('.tmp/tw.png', px, 700, 700);
console.log('ok');
