// src/generators/environment/ezTree.js
// Round-canopy trees, generated by the vendored ez-tree library
// (src/vendor/ez-tree, MIT-licensed, https://github.com/dgreenheck/ez-tree)
// instead of this project's own hand-rolled clump/lobe system — a real
// recursive branch hierarchy (trunk -> branches -> twigs) with individual
// leaf billboards, rather than a handful of solid foliage blobs. This is
// the first place in the game that uses real bark/leaf textures instead of
// flat procedural color — see propMetrics.js's EZ_TREE_SCALE/
// EZ_TREE_TRUNK_RADIUS comment for why collision doesn't need to care.
import * as THREE from 'three';
import { Tree } from '../../vendor/ez-tree/ez-tree.es.js';
import { createRng } from '../seededRandom.js';
import { sampleTree, EZ_TREE_SCALE } from '../../sim/propMetrics.js';
import { getToonGradientMap } from '../../render/toonGradient.js';
import { applyWindSway } from '../../render/windSway.js';

// One preset for every round tree, same idea as the old system having one
// shape template varied by seed rather than picking between silhouettes —
// ez-tree's own seeded branch angle/gnarliness variation already gives each
// tree a distinct shape from this one template. Oak Small specifically: the
// smallest/cheapest preset (~6800 tris vs. Medium/Large's 14k-23k) — still
// far heavier than the old blob canopy (~700 tris total), so this is the
// conservative end of what ez-tree offers, picked for a scatter-brushed
// forest of many trees rather than a handful of hero trees.
const PRESET_NAME = 'Oak Small';

/** MeshPhongMaterial -> MeshToonMaterial, keeping this game's stylized look consistent across every asset, tree included. Bark's normal/ao/roughness maps don't carry over — MeshToonMaterial doesn't support them, same tradeoff toonify()'s own MeshStandardMaterial conversion already makes elsewhere (see render/scene.js). */
function toToonMaterial(mat) {
  return new THREE.MeshToonMaterial({
    color: mat.color,
    map: mat.map || null,
    gradientMap: getToonGradientMap(),
    transparent: mat.transparent,
    alphaTest: mat.alphaTest || 0,
    side: mat.side,
  });
}

const BASE_CHILDREN = { 0: 4, 1: 2, 2: 3 }; // Oak Small's own defaults — density 1.0 baseline
const BASE_LEAF_COUNT = 14; // ditto
const DEFAULT_LEAF_DENSITY = 1.5; // what shipped before this became a slider — see World Editor Scatter mode

/**
 * @param {number} seed
 * @param {number} [leafDensity] world.treeSettings.leafDensity, or a
 *   per-prop override (see the World Editor's Place tab). Clamped 0.5-3.5.
 *
 *   ONLY the deepest branch level (2, the one that actually grows leaves —
 *   see the big comment below) scales fully with density; levels 0/1 (the
 *   trunk's own scaffold branches) are capped much lower. Scaling every
 *   level by the same multiplier — what an earlier version of this
 *   function did — compounds combinatorially (level0 x level1 x level2
 *   branch count) and most of that growth is BARE WOOD, since only level
 *   2's children get leaves at all: at density 3 the old formula produced
 *   ~650 branches, the overwhelming majority leafless, which is exactly
 *   the "hairy explosion of bare sticks poking out of the canopy" bug
 *   Dennis reported. This version keeps the scaffold roughly the same
 *   shape as the un-scaled preset and grows the leaf-bearing twig count
 *   instead, which is the only lever that actually makes the CANOPY denser.
 * @returns {THREE.Group} a posed, textured tree standing on y=0
 */
export function generateEzTree(seed, leafDensity) {
  // Replays the exact same draw sequence sampleTree's caller (collision.js,
  // via propCollider's 'trunk' case) uses for this seed, so rotationY/scale
  // land on the same values client and server agree on — this function
  // doesn't use trunkColor/leafColor/trunkHeight (ez-tree's own preset owns
  // those now), but the draw sequence still has to be replayed in full.
  const d = sampleTree(createRng(seed), { type: 'round' });
  const density = Math.max(0.5, Math.min(3.5, leafDensity || DEFAULT_LEAF_DENSITY));

  const tree = new Tree();
  tree.loadPreset(PRESET_NAME);
  // Birch bark (pale, not Oak Small's default warm brown) + Aspen leaves
  // (small and round, closer to a real birch's leaf shape than Oak's large
  // lobed ones) — matches the reference look Dennis asked for. Set after
  // loadPreset (which copies the WHOLE preset JSON over tree.options,
  // including bark.type/leaves.type) and before generate() picks them up.
  tree.options.bark.type = 'birch';
  tree.options.leaves.type = 'aspen';
  // this.options.branch.levels is 3 for Oak Small — level 3 branches are
  // the terminal twigs that grow leaves (see ez-tree's own generateBranch:
  // leaves only ever spawn "if branch.level === options.branch.levels").
  // children[0]/children[1] decide how many level-1/level-2 branches
  // exist — capped at a mild 1.3x/1.6x regardless of density so the
  // visible scaffold doesn't multiply out. children[2] decides how many
  // LEAFY level-3 twigs grow off each level-2 branch — this is the one
  // that scales fully with density, since it's the only lever that adds
  // leaf coverage without also adding bare-wood clutter.
  tree.options.branch.children = {
    0: Math.max(1, Math.round(BASE_CHILDREN[0] * Math.min(density, 1.3))),
    1: Math.max(1, Math.round(BASE_CHILDREN[1] * Math.min(density, 1.6))),
    2: Math.max(1, Math.round(BASE_CHILDREN[2] * density)),
  };
  tree.options.leaves.count = Math.max(4, Math.round(BASE_LEAF_COUNT * density));
  // Leaves shrink and start closer to each branch's base as density climbs
  // — smaller so a denser cluster doesn't just overlap itself into a
  // brighter blob, closer-to-base so coverage spreads along the whole
  // branch length instead of bunching at the tip.
  tree.options.leaves.size = Math.max(0.7, 1.38 - 0.12 * (density - 1));
  tree.options.leaves.start = Math.max(0.02, 0.16 - 0.025 * (density - 1));
  // A pure-white leaf tint (ez-tree's own default) has lightness=1, and
  // applyColorTint's hue/saturation retarget always preserves the
  // material's OWN lightness — at l=1 every hue renders as white, so
  // per-tree leaf recoloring would be a visible no-op. A mid grey keeps
  // the untinted look natural (a neutral multiply only dims the texture,
  // doesn't shift its hue) while giving tinting a real lightness to work
  // from.
  tree.options.leaves.tint = 0xb0b0b0;
  // ez-tree's own internal RNG (independent of sim's) — reusing the same
  // numeric seed is harmless (two unrelated generators) and keeps "same
  // seed -> same tree" true for this function on its own.
  tree.options.seed = seed;
  tree.generate();

  const branchMat = toToonMaterial(tree.branchesMesh.material);
  tree.branchesMesh.material.dispose();
  tree.branchesMesh.material = branchMat;
  tree.branchesMesh.userData.preserveMaterial = true;
  // Leaf-color recoloring (World Editor Place tab's per-prop color picker,
  // via applyColorTint in render/scene.js) must never touch the trunk —
  // "an option to change the color of the leaves only" is exactly what
  // this opts the bark mesh out of.
  tree.branchesMesh.userData.excludeFromColorTint = true;

  const leafMat = toToonMaterial(tree.leavesMesh.material);
  tree.leavesMesh.material.dispose();
  tree.leavesMesh.material = leafMat;
  tree.leavesMesh.userData.preserveMaterial = true;
  tree.leavesMesh.userData.isTreeLeaves = true; // per-frame uTime update — see updateWindSwayTime in scene.js

  // Sway strength grows from 0 at the lowest leaf up to full strength at
  // the canopy's top (measured off this tree's own actual leaf geometry,
  // not a guessed constant, since leaf height varies by branch shape/seed)
  // — without a gradient the whole canopy would shear sideways as one
  // rigid slab, which is the exact "multi-part object" failure windSway.js
  // warns about.
  tree.leavesMesh.geometry.computeBoundingBox();
  const leafHeight = tree.leavesMesh.geometry.boundingBox.max.y;
  applyWindSway(leafMat, { height: leafHeight, strength: 0.6, speed: 1.1 });

  if (d.rotationY !== null) tree.rotation.y = d.rotationY;
  tree.scale.setScalar(EZ_TREE_SCALE * d.scale);

  return tree;
}
